SLAC/slac-drupal-profile-theme

source/03-components/card/_card.scss
The padding for this is unique on desktop, but should be consistent with other cards on mobile.
=> 79 & 82 - fix padding on teaser card

includes/paragraph.inc, slac.style_options.yml, templates/paragraph/paragraph--overlap-image.html.twig
We do need to make one change outside of the theme - the "override caption" field is marked as required which means I can't set it to false.
I had to hook up the preprocess function but it all seems to be outputting correctly now.
=> 75 - overlap images integration

source/02-layouts/section/section.stories.jsx
In keeping with the designs: removes the section intro & buttons, adds lede styling to the first column
=> adjust 2:1:1 content to match designs better

source/03-components/alert-bar/alert-bar.scss, templates/misc/sitewide-alert.html.twig
- adds a 'complementary' landmark around the alert bar (seemed like the best fit)
- enforce inherited colors inside - we will probably still want Lynn to update the field for basic formatting only, but this will make sure any styling doesn't break contrast
=> 95 - fix a11y issues with alert bar

source/03-components/kicker/_kicker.scss, templates/content/node--news-article--card.html.twig
The kicker style also got more spaced-out at some point, based on figma.
=> 72 - add 'news' label to news article cards

source/03-components/arrow-link/arrow-link.es6.js, templates/content/node--news-article--teaser.html.twig
- updates field name so fallback image displays as needed
- adds a check to the arrow-link script to keep it from applying more than once to the same element
=> 81 - fix issues with article teaser

source/03-components/form-item/_form-item.scss
The only types that actually spill out wider without the extra rule aren't types we're using, but no harm in fixing it while I'm in here.
=> add wysiwyg-size constraint to webform

source/00-config/config.design-tokens.yml, source/03-components/media-lightbox/media-lightbox.scss
Setting it to 501 still puts it behind the logged-in admin bar, have to go a bit higher.
=> 111 - higher z-index for lightbox

source/03-components/figure/_figure.scss
https://forumone.slack.com/archives/C03HMMGKVNZ/p1673045880296359
Jess noticed that floated images weren't limited in width inside wysiwygs - it looks like the classes being applied don't 100% match the styles. I left both in just in case anything else depends on the `u-` versions.
=> re-apply wysiwyg figure styling

source/03-components/card/_card.scss, templates/content/node--event--card.html.twig, templates/content/node--event--large-card.html.twig
- paragraphs inside cards shouldn't have bottom margins (there's already padding)
- changes linebreak in composed date to a " · "
=> 129 - fix spacing issues inside event cards

source/02-layouts/sidebar/_sidebar.scss, templates/content/node--publication--full.html.twig
Corresponding config update in the other repo.
Also noticed that if the page content is really short, you can still get the sidebar colliding with the footer, so tiny css change there.
=> 125 - update template to use Tags tax

source/03-components/search/_search.scss
The calculation should take into account the alert bar and the drupal admin bar if they're present.
=> 251 - adjust search form positioning

source/02-layouts/header/_header.scss, templates/content/node--blog--full.html.twig
this accidentally includes part of the work for another ticket (blog category); there will still be a config update for that in the other repo.
also, looks like the gin library changed its variable names on us, so a small fix to position the header correctly while logged in.
=> 270 - fix spacing in header (nav gets own line)

templates/content/node--blog--full.html.twig
thanks for the help debugging - i just assumed "label" meant "string". drupal's a little weird sometimes!
=> 337 - display blog category on detail

source/03-components/card/card--small/_card--small.scss
per yesterday's thorough discussion, small/square cards will now match height within rows, and it's up to content editors to limit their text to fit. i also noticed some icons get cut off - i think the explicit width was a holdover from before we implemented fontawesome. tweaked for better display.
=> 312 - small card height

source/03-components/hero-bg-image/hero-bg-image.scss, source/03-components/social-share/social-share.scss
moving the overlay with `position: relative` was leaving an undesired big gap underneath it, margin fixes this. also fixed a little misalignment i noticed in the social share bar.
=> 274 - hero w/overlay positioning

source/03-components/accordion/_accordion-item-content.twig, source/03-components/search/modules/SearchFlyout.es6.js
This is a quirky one - it works as intended right now if you're using the tab key or voiceover, but specifically if you're navigating by arrow in nvda, it reads out the search fields even when they're collapsed. This seems to sort it out, but I was just testing with browser tools since my dev machine can't run nvda; I'll go back and confirm it works once merged.
also includes a fix for over-described buttons in the accordion
=> 279 - nvda reads search without aria-hidden

includes/node.inc
When a `news_article` has no paragraphs, the card display breaks:
Here we fix the `node.inc` file to correctly check for a #formatter key before it checks the content of the key.
=> Fixed news behavior when there are no paragraphs

source/03-components/arrow-link/arrow-link.es6.js, source/03-components/arrow-link/arrow-link.yml, source/03-components/external-link/external-link.es6.js, source/03-components/external-link/external-link.twig
We'll now traverse link elements to find the last Text Node of the element, rather than working with textContent and innerHTML. This allows us to work with nodeValue, which remains unescaped. It also allows us to act on links that have markup in the text.
=> Fix arrow and external links with html special entities in last word

includes/node.inc, source/03-components/event-details/event-details.scss, source/03-components/event-details/event-details.twig
To use this functionality on a site, add a `field_require_auth` field to the Event content type.
See also: https://github.com/SLAC/slac-drupal-profile/pull/132
=> Support putting event details behind auth wall

slac.libraries.yml, source/02-layouts/subfooter/subfooter.twig
Adding a query parameter to cache the updated logo in the CDN.
Change styles.css to a base weight to ensure it's loaded in the order overriding stylesheets expect.
=> Ensure updated logo is displayed and CSS is loaded in correct order
