SLAC/slac-drupal-profile-theme

includes/node.inc
Companion to https://github.com/SLAC/slac-alpha-d9/pull/69
=> [SLACDP22-159] Add is_truncated variable for news view modes

templates/content/node--news-article--card.html.twig, templates/content/node--news-article--teaser.html.twig
Don't let the big diff fool you, it's mostly whitespace - just had to update the media settings. Also fixed a typo in the other view.
Is there anything special I need to know about our workflow now that the theme is in its own repo? Looks like there's no integration branch?
=> 81 - news article teaser int

source/03-components/section-search/_section-search.scss, source/03-components/section-search/section-search.twig
QA flagged that the focus state was a little too subtle here so I've added an outline to the button. Had to get slightly fancy with it due to mask-image.
=> 28 - section search focus

source/02-layouts/section/_section.scss, source/02-layouts/section/section.stories.jsx
Pretty minimal, just a new layout.
=> 206 - 2:1:1 section layout

source/03-components/_index.scss, source/03-components/citation/_citation.scss, source/03-components/citation/citation.stories.jsx, source/03-components/citation/citation.twig, source/03-components/citation/citation.yml
Nothing fancy, specific field logic will be handled in integration.
=> 84 - citation

source/01-global/html-elements/00-universal/_universal.scss, source/03-components/form-item/form-item--checkbox/_form-item--checkbox.scss, source/03-components/form-item/form-item--radio/_form-item--radio.scss
Didn't need to integrate much here, just tweaked a few things based on the style guide example form.
=> 108 - webform integration

slac.style_options.yml, templates/paragraph/paragraph--section-fixed.html.twig
There's also a PR on the main repo for a config change to the field display.
=> 208 - fixed section integration

source/03-components/event-details/event-details.scss
=> 121 - add styling for "add to calendar"

templates/content/node--blog--full.html.twig
Copied over the changes from the news article template and everything looks good now.
=> 120 - blog detail page - fix author link

source/03-components/card/card--small/_card--small.scss, templates/paragraph/paragraph--small-card-with-icon.html.twig
Fixes issue 2b where the icons were too large & getting cropped.
=> 76, 2b - fix icon sizing on small cards

source/03-components/citation/citation.twig, source/03-components/citation/citation.yml, templates/content/node--publication--teaser.html.twig
There's a lot of field_value and render happening here - generally speaking, the fields wouldn't render correctly without them. Either strings would come out as "Array" or html tags wouldn't render as needed. Open to any advice on this.
=> 85 - publication teaser citation

source/04-templates/people-profile/people-profile.twig, source/04-templates/people-profile/people-profile.yml, templates/content/node--person--full.html.twig
Sounds like the 'components' field may be changing, but hopefully that doesn't require any major updates here.
=> 124 - integrate people detail page

templates/content/node--blog--card.html.twig, templates/content/node--blog--teaser.html.twig
(there's also a PR in the other repo to update the field display)
=> 126 - add series kicker, "blog post" tag to blog cards

source/04-templates/publication-detail/publication-detail.twig, templates/content/node--publication--full.html.twig
I think everything's hooked up ok, I modeled it after other templates.
=> 125 - integrate publication detail

templates/content/node--person--teaser.html.twig
Just needed some small tweaks. Config update in the other repo.
=> 53 - update bio teaser card

source/04-templates/people-profile/people-profile.scss, source/04-templates/people-profile/people-profile.twig, templates/content/node--person--full.html.twig
adds the mailstop, adjusts some spacing, puts links and affiliations on their own lines. There's also a tiny PR in the other repo for the field display change.
=> 124 - updates to person detail

source/03-components/button/_button.scss, templates/content/node--news-article--teaser.html.twig
4 - adjusts the kicker text
5 - tweaks button spacing (I think this is overall a good change for button spacing logic in wysiwygs, but we should keep an eye out for regressions)
=> 127 - news listing page fixes

templates/content/node--blog--large-card.html.twig
most of the diff is whitespace reformatting, all that really changed is the kicker text & the type label. corresponding config update in the other repo.
=> 126 - blog large card display update

templates/paragraph/paragraph--two-column-hero.html.twig
There's a corresponding config update in the other repo.
=> 127 - add rss url to two col hero

source/03-components/search/_search.scss, templates/layout/page--search.html.twig
Looks like the wrong template was being inherited, the header should show up as expected now. Also fixed the padding issues in the field.
=> 92 - fix visual issues on search page

source/02-layouts/sidebar/_sidebar.scss, templates/field/field--field-topics.html.twig
from ticket:
- 1c: topics area displaying incorrectly
- 2a: lack of padding below sidebar on mobile
=> 125 - fix spacing, tag display on publication

templates/content/node--event--large-card.html.twig
Show event type as a kicker, same logic as the other event card.
=> 129 - update large card display

source/03-components/search/_search.scss
@kmonahan thanks for looking at this first, it was as easy of a fix as you thought :) i added the fallbacks for the header height var just for consistency.
=> 261 - add css var fallbacks for search

templates/content/node--news-article--large-card.html.twig
most of the diff is whitespace formatting, only update is the kicker text
=> 310 - update kicker/type on news large card

source/00-config/mixins/_focus.scss, source/00-config/mixins/_variables.scss, source/03-components/alert-bar/alert-bar.scss
i really like how these variables are set up! let me know if you're aware of anywhere else i need to make updates.
=> 198 - lighter focus outlines on blue bgs

source/00-config/config.design-tokens.yml, source/03-components/menu/menu--side/menu--side.scss
per the design example, adds motion when you hover an already-active item
=> 327 - hover effect on nav

source/03-components/overlap-image/_overlap-image.scss, templates/field/field--field-button-links.html.twig, templates/paragraph/paragraph--overlap-image.html.twig
corresponding config update in the other repo
=> 313 - buttons in overlap image para

includes/navigation.inc, includes/paragraph.inc
- [SLACDP22-288] Remove reference to field_boolean
- [SLACDP22-288] Fix error when indexing via cron
=> [SLACDP22-288] Remove field reference; fix indexing warning

source/03-components/pager/_pager.scss
Made some tweaks so pagination arrows & the hr above it will inherit from their surroundings.
=> 384 - fix pagination colors

source/02-layouts/subfooter/subfooter.twig, source/03-components/logo/logo.twig
Same behavior as the main site.
=> 393 - add links to global footer

templates/content/node--homepage--full.html.twig
I was able to get the right spacing after all, just needed to shift a few containers around.
=> 407 - title spacing/centering on homepage

slac.style_options.yml, source/01-global/html-elements/20-unordered-list/_unordered-list.scss, source/01-global/html-elements/21-ordered-list/_ordered-list.scss, source/02-layouts/section/_section.scss, source/02-layouts/section/section.stories.jsx, source/02-layouts/subfooter/_subfooter.scss, source/03-components/promo-box/_promo-box.scss, templates/content/node--event--card.html.twig, templates/content/node--event--large-card.html.twig, templates/content/node--event--list-card.html.twig, templates/content/node--event--teaser.html.twig
368, 383, 402, and 404 - these were all pretty small. There is still one more update to make to the event display for 368, but that's a config change around the Smart Date Formatter so I think it'll be in the other repo.
Edit: also added 356/374, which are both about nested list styles.
=> Slacdp22 - misc uat fed

source/03-components/search/search.twig
Hi KJ. Could you review and merge this pull request if it looks good? Thanks.
=> change to "Search this site" and "Search people"

config/schema/slac.schema.yml, includes/media.inc, includes/navigation.inc, includes/paragraph.inc, source/02-layouts/internal-header/internal-header.twig, source/02-layouts/internal-header/internal-header.yml, source/03-components/external-link/external-link.es6.js, source/03-components/external-link/external-link.twig, theme-settings.php
- Allow external link icons to be turned off
- Resolve PHP deprecation warnings
- Set default value for SLAC Today header link
This is a companion to https://github.com/SLAC/slac-drupal-profile/pull/104.
=> Allow external link icons to be turned off and bugfixes

includes/region.inc, source/03-components/search/_search-input.twig, source/03-components/search/_search.scss, source/03-components/search/search.es6.js, source/03-components/search/search.twig
- Ensure SLAC Web search gets positioned correctly when the search menu is hidden
- Load `include_slac_web_search` setting value from the active theme
- Add (Beta) label to SLAC Web search option
=> SLAC Web search bugfixes

source/03-components/arrow-link/arrow-link.es6.js, source/03-components/external-link/external-link.es6.js
- **Fix link last word rendering**
- **Prevent lock icon from being added to absolute links on current internal site**
=> External and arrow link bugfixes

source/03-components/mobile-menu/modules/_MobileMenu.es6.js, source/03-components/search/modules/YurtsHelpers.es6.js, source/03-components/search/search.es6.js
- **Gracefully handle Yurts outages**
- **Use new phonebook endpoint**
- **Remove aria-hidden attribute from mobile search form**
=> Search updates

source/03-components/external-link/external-link.es6.js
- In previous bugfixes we started removing the last word wrapping span before checking to see whether the link was an external or locked link, resulting in the arrow being removed
- We're also now checking for locked parent domains and locking links only if the link goes to a different child site
=> Ensure CTA links have appropriate icon

source/03-components/media-lightbox/media-lightbox.scss
Reverts SLAC/slac-drupal-profile-theme#219
This needs more work. Moving to Q3.
=> Revert "Display lightbox caption and credit on mobile"
